### ISSUE TITLE
nginx without http-rewrite

### ISSUE THREAD

**Issue by shouhouhuakai** [dna2github/dna2oslab#10]
I find that the when I write "rewirte" in nginx.conf, I get this error,"nginx: [emerg] unknown directive "rewrite" in ./conf/nginx.conf:5", and when I find the nginx configure, I find that "--without-http_rewrite_module".

**Comment by dna2github** [comment]
sorry for late response and nginx compling is in experimental stage. i do not have time to fix it now. but maybe will spend some time to make nginx compiling from source not a hack way in future. you are welcome to do some contributions.

**Comment by dna2github** [comment]
this is fixed in the buildv2
