### ISSUE TITLE
how to dec file with name bin-node-v8.4.0, i dont know file type (mac os)...

### ISSUE THREAD

**Issue by liulover5** [dna2github/dna2oslab#11]
how to extra file with name bin-node-v8.4.0, i dont know file type (mac os)...
ll cmd like this:
anddeMac-mini:bin_android and$ ll
-rw-r--r--@  1 and  staff  19020848 11  5 21:56 bin-node-v8.4.0
file is zip , tar tar.gz or other i cannt unzip it .   
any example ?

**Comment by dna2github** [comment]
not sure why i just see the issue. sorry for the late response. it is a binary; if you vim bin-node-v8.4.0 it has elf header. and it is a binary for android over arm. you need to copy it to an android machine and `chmod 755` then execute it.
