### ISSUE TITLE
编译haproxy提示缺少文件。

### ISSUE THREAD

**Issue by cjjdaq** [dna2github/dna2oslab#13]
cat: /root/dna2oslab/android/build/haproxy/config.h: No such file or directory
提示缺少文件
可以帮忙编译个（armv8）aarch64 的haproxy吗

**Comment by dna2github** [comment]
wow, sorry that I miss upload `config.h`. will fix soon.

**Comment by dna2github** [comment]
fix in https://github.com/dna2github/dna2oslab/commit/96220327c6152751e557bbf97c3ffb5508ee38e0
you can `git pull` and build again. sorry for late response.
