### ISSUE TITLE
可以提供.a文件的导入库和头文件吗？

### ISSUE THREAD

**Issue by xnetsc** [dna2github/dna2oslab#15]
如题。
这样也方便我自己写native的扩展。

**Comment by dna2github** [comment]
你是指nodejs的.a文件么，我可以上传给你。稍等。

**Comment by dna2github** [comment]
[node-v10.15.3.tar.gz](https://github.com/dna2github/dna2oslab/files/3170935/node-v10.15.3.tar.gz)

node-v10.15.3 arm package.

**Comment by mccoysc** [comment]
@dna2github 没看到.a文件在哪
