### ISSUE TITLE
it's not a problem it's just that I don't understand

### ISSUE THREAD

**Issue by azkadev** [dna2github/dna2oslab#16]
how to fill this?
``` bash
export ENVSRCTARBALL=""
export HOST_GCC_DIR=""
```
I don't know where can you explain in detail?

I'm using linux based debian thank you

**Comment by dna2github** [comment]
- `export ENVSRCTARBALL=""` # /path/to/source/folder; source tarballs are downloaded to the folder
- `export HOST_GCC_DIR=""` # /path/to/gcc-x.x; host gcc, for example compile nodeJS 14 requires host gcc version > 6; most of time you can ignore this var
