### ISSUE TITLE
每次运行nginx都会在bin-nginx-1.10.2所在目录下产生一个error.logs

### ISSUE THREAD

**Issue by hjcgqj** [dna2github/dna2oslab#17]
你好：
   我这边每次在Android系统下运行nginx都会在bin-nginx-1.10.2所在目录下产生一个error.logs，请问这个文件是如何产生的，又该如何配置这个文件的目录。

此致
敬礼

**Comment by dna2github** [comment]
在做完configure以后会有一个ngx_auto_conf.h，里面可以配置，如果设置的是相对路径比如 `.` 那么这些文件就会产生到运行nginx的地方(CWD); 而且这个error log是也可以在nginx.conf里配置的…

**Comment by hjcgqj** [comment]
@dna2github ，error.log可以在nginx.conf或ngx_auto_conf.h中进行配置，但是实际上nginx运行的时候仍然会产生一个error.logs文件，用来收集系统错误而非nginx运行时产生的错误，这个error.logs可以在什么地方进行路径配置

**Comment by dna2github** [comment]
`nginx.conf`

**Comment by hjcgqj** [comment]
@dna2github ,这个该如何配置呢，请指导一下

**Comment by dna2github** [comment]
搜索引擎 ningx.conf；这个是nginx的配置；如果要指定配置文件nginx运行的时候 `-c`
