### ISSUE TITLE
运行nginx-1.18.0.sh时报错

### ISSUE THREAD

**Issue by hjcgqj** [dna2github/dna2oslab#19]
你好博主，我这边部署工程之后，运行nginx-1.18.0.sh会出现如下错误
/home/hjc/Desktop/dna2oslab-master/android/buildv2/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang --build=x86_64-linux --host=arm-eabi --target=arm-eabi   -L/home/hjc/Desktop/dna2oslab-master/android/nginx-1.18.0/../dist/pcre-8.44/lib -L/home/hjc/Desktop/dna2oslab-master/android/nginx-1.18.0/../dist/zlib-1.2.11/lib conftest.c  >&5
clang: error: unsupported option '--build=x86_64-linux'
clang: error: unsupported option '--host=arm-eabi'

**Comment by dna2github** [comment]
sorry for inconvenience. 问题是新的ndk已经有点变化了，这个脚本还是gcc时候的没check过，很快会fix…

**Comment by dna2github** [comment]
fixed in https://github.com/dna2github/dna2oslab/commit/4b8a3cb883bdbbcf776665de6b7d517b8d8875f5
