### ISSUE TITLE
方便提供个nginx的arm64-v8a的静态库吗？

### ISSUE THREAD

**Issue by fengpeitian** [dna2github/dna2oslab#21]
我想在android上用nginx搭建一个rtmp服务器，不知如何编译出.so或者.a来方便android集成和代码调用?

**Comment by dna2github** [comment]
为何要编译出 so或者a？那个需要你自己写代码。或者你直接在 https://github.com/dna2github/dna2oslab/releases/tag/0.3.1-android-gt6-arm64 下载nginx的binary文件，然后在你的app里run一个process就可以了，具体案例可以参考README里提到的nginx使用 https://github.com/dna2github/dna2mtgol/tree/master/fileShare

**Comment by fengpeitian** [comment]
写代码是ok的 我也是android开发，对于这个库不是很熟悉，但是我仍然想它能够被编译成.a文件，最好还可以集成rtmp模块，可以用来推流服务器 还请大佬帮忙看下有没有方案

**Comment by dna2github** [comment]
这个repo的这个文件夹只是编译nginx的脚本，所以如果你要编译rtmp的话，可以把代码下载下来，然后在nginx编译脚本sh里的configure那行加上你的module就可以编译出nginx了。我并没有看到编译nginx会产生任何.a文件…
