### ISSUE TITLE
release里nginx-1.18.0.tar.gz运行报错

### ISSUE THREAD

**Issue by Kinvn** [dna2github/dna2oslab#22]
kona:/cache/nginx-1.18.0 # ./sbin/nginx -c conf/nginx.conf
nginx: [alert] could not open error log file: open() "/opt/lab/dna/dna2oslab/android/buildv2/../nginx-1.18.0/dist//logs/error.log" failed (2: No such file or directory)
2024/01/15 09:27:15 [emerg] 29213#0: open() "/opt/lab/dna/dna2oslab/android/buildv2/../nginx-1.18.0/dist//conf/nginx.conf" failed (2: No such file or directory)

我自己尝试编译但是无法通过，是否有可以直接运行的arm64位二进制文件

**Comment by dna2github** [comment]
哦，这个是忘了把config.h里默认的找config基础路径改掉导致的，你可以试试 `./sbin/nginx -c <绝对路径>`，等有时间了，我重新编译下，上传fixed版本，顺便升级下nginx版本
