### ISSUE TITLE
[build_base] replace gcc to clang

### ISSUE THREAD

**Issue by dna2github** [dna2github/dna2oslab#7]
since ndk will drop gcc and use clang, need to spend some time to switch build script to use clang.

**Comment by aschrijver** [comment]
Is this what I am referring to here for Node compile: https://github.com/nodejs/node/issues/14771 ?

**Comment by dna2github** [comment]
No, it is for https://developer.android.com/ndk/downloads/revision_history.html
`GCC is no longer supported.` thus need to rebuild nodeJS with clang and make sure it pass.

**Comment by aschrijver** [comment]
Ah okay.

BTW J2V8 @drywolf has a beautiful build system in the works, that I have been test-driving yesterday: https://github.com/eclipsesource/J2V8/pull/327

Here are my compilation results: https://github.com/nodejs/node/issues/14783
And you probably had seen this already: https://stackoverflow.com/a/45649995/8295283

**Comment by dna2github** [comment]
built node-v10.10.0 with clang using modified version of `android-configure`; the configure shell script is provided by node source code. tested on Android 6; works! will get script checked-in soon.
