### ISSUE TITLE
Node 7.1.0 script runs well up-to 7.10.1

### ISSUE THREAD

**Issue by aschrijver** [dna2github/dna2oslab#9]
This issue is just FYI, feel free to close.

Thanks for writing your build script. It compiled node as executable and helped solve some errors when trying to compile as a library. But still I didn't manage to get a full library compile after a day of trying.

I have documented my findings on stackoverflow - [Viable options to running NodeJS on Android (Aug 2017)](https://stackoverflow.com/a/45649995/8295283) where you are also mentioned a number of times.

**Comment by dna2github** [comment]
close the issue; currently support build up to node-v8.4.0.
